SELECT * FROM LIVROS;

SELECT NOME_LIVRO FROM LIVROS;

SELECT ID_LIVRO AS 'CODIGO DO LIVRO' FROM LIVROS;

SELECT * FROM LIVROS
WHERE CATEGORIA = 'BIOGRAFIA';

-- 1 UMA TABELA COM OS ROMANCES QUE CUSTAM MENOS DE 48 REAIS.
SELECT * FROM LIVROS
WHERE CATEGORIA = 'ROMANCE' AND PREÇO < 48;

-- 2 FICÇAO DO FRANK HERBERT E PARA NAO SER DO FRANK HERBERT
SELECT * FROM LIVROS
WHERE CATEGORIA = 'Ficção científica' AND
(AUTORIA = 'FRANK HERBERT');

SELECT * FROM LIVROS
WHERE CATEGORIA = 'Ficção científica' AND NOT
(AUTORIA = 'FRANK HERBERT');

/*
SELECT CIDADE, ESTADO
FROM MAPA
WHERE CIDADE LIKE '%LÂNDIA';
*/

SELECT * FROM VENDAS;

SELECT DISTINCT  ID_LIVRO FROM VENDAS; -- SEM REPETIR

SELECT DISTINCT  ID_LIVRO FROM VENDAS
WHERE ID_VENDEDOR = 1
ORDER BY ID_LIVRO; -- VENDIDOS PELO VENDEDOR 1 E ORDENADO 


DELETE FROM LIVROS WHERE ID_LIVRO = 8; --  DELETANDO PELO ID

UPDATE LIVROS SET PREÇO = 0.9 * PREÇO;
