SELECT VENDAS.ID_VENDEDOR, 
    VENDEDORES.NOME_VENDEDOR, 
        SUM(VENDAS.QTD_VENDIDA)
FROM VENDAS, VENDEDORES
WHERE VENDAS.ID_VENDEDOR = VENDEDORES.ID_VENDEDOR 
GROUP BY VENDAS.ID_VENDEDOR, VENDEDORES.NOME_VENDEDOR  -- FILTRANDO USANDO DUAS TABELAS.


/*
Usando um apelido com o comando AS e referenciando esse apelido nos campos selecionados na consulta.

SELECT A.NOME_LIVRO,
           B.QTD_VENDIDA
FROM LIVROS AS  A,  VENDAS AS  B
WHERE B.ID_LIVRO = A.ID_LIVRO;

SELECT A.NOME_LIVRO,
           B.QTD_VENDIDA
FROM LIVROS  A,  VENDAS   B
WHERE B.ID_LIVRO = A.ID_LIVRO;

*/

SELECT VENDAS.ID_VENDEDOR, 
    VENDEDORES.NOME_VENDEDOR, 
        SUM(VENDAS.QTD_VENDIDA)
FROM VENDAS INNER JOIN VENDEDORES
ON VENDAS.ID_VENDEDOR = VENDEDORES.ID_VENDEDOR 
GROUP BY VENDAS.ID_VENDEDOR, VENDEDORES.NOME_VENDEDOR 

-- funções de agregação - Métricas

/*
MAX: a partir de um conjunto de valores é retornado o maior entre eles;
MIN: analisa um grupo de valores e retorna o menor entre eles;
SUM: calcula o somatório dos valores de um campo específico;
AVG: realiza a média aritmética dos valores de uma determinada coluna; e
COUNT: contabiliza a quantidade de linhas selecionadas.
-- 
SELECT MAX(QTD_VENDIDA) FROM VENDAS;

SELECT MAX(QTD_VENDIDA) FROM VENDAS
GROUP BY(ID_VENDEDOR);
-- 
*/


-- SERA QUE TODOS OS LIVROS DESSA TABELA FORAM VENDIDOS?

SELECT LIVROS.NOME_LIVRO,
    VENDAS.QTD_VENDIDA
FROM LIVROS LEFT JOIN VENDAS
ON LIVROS.ID_LIVRO = VENDAS.ID_LIVRO
WHERE VENDAS.QTD_VENDIDA IS NULL;

SELECT 
    VENDAS.ID_LIVRO,
    LIVROS.NOME_LIVRO,
    VENDAS.QTD_VENDIDA
FROM LIVROS RIGHT JOIN VENDAS
ON LIVROS.ID_LIVRO = VENDAS.ID_LIVRO;
